test: &default

  # Credentials for REST APIs
  client_id: 
  client_secret: 

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: 
  username: 
  password: 
  signature: 
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: 

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  client_id: 
  client_secret: 
  mode: live
