test: &default

  # Credentials for REST APIs
  client_id: Ab2OEun1GjD-p4xlEXh49yzGPc0XY_rnAY5Dqe_c_vMio42IRtytrUPN0_KpbyvNNGK_SJtNjMSQhJzX
  client_secret: EDZAXvTD7sV3o3OAJlOPu5BHk37MeyMKsf30fH8UmmkE7n3mzir6I1S-IwLYLwWMs0cA8FjS_spBUix5

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: codigofacilito@facilito.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
